### ISSUE TITLE
As a player, I would like a fancy looking main menu

### ISSUE THREAD

**Issue by patatos12321** [patatos12321/TopDownDrift#13]
- [x] The main menu allows the player to navigate to the free roam scene
- [x] The free-roam scene has a button to go back to the main menu
- [x] The main menu looks cool.
  - For this requirement to be met, at least one curse word must be heard when showing the menu to someone

**Comment by patatos12321** [comment]
I still need to meet the final requirement, waiting for someone to show the menu to. hopefully he curses

**Comment by Olivier-Gauvin** [comment]
unfortunatly  I did not curse...

also, I would lower the "FREE ROAM" button on the UI to pos-y -275 as to not hide the game title when resolution is in 16:9.

Regarding the last requirement. I think adding a drifting 2d car with trailing smoke in the top right corner could help fullfilling this requirement.
